# General site info
title: Color Room Films
email: info@colorroomfilms.com
description: Motion Picture Memories you'll cherish forever
baseurl: ""
url: "https://colorroomfilms.com"
author: colorroomfilms

# Social links
twitter:
  username: colorroomfilms
facebook:
  app_id: 946947812026207
  publisher: 946947812026207
  admins: 946947812026207
logo: /img/logo.svg
social:
  name: colorroomfilms
  links: "https://www.facebook.com/colorroomfilms/"
  links: "https://twitter.com/colorroomfilms"
  links: "https://www.instagram.com/color_room_films/"
  links: "https://plus.google.com/106778430374036459605"
  links: "https://www.youtube.com/channel/UCeeC4ieZCDdZzxIYZeGgHKQ"
  links: "https://vimeo.com/colorroomfilms"
  links: "http://www.weddingwire.com/reviews/color-room-films-jackson/fd77ea76d63e4a5f.html"
  links: "https://www.theknot.com/marketplace/color-room-films-llc-jackson-nj-963435"

facebook_url: "https://www.facebook.com/colorroomfilms/"
facebook_title: "Add Color Room Films on Facebook"

twitter_url: "https://twitter.com/colorroomfilms"
twitter_title: "Follow Color Room Films on Twitter"

instagram_url: "https://www.instagram.com/color_room_films/"
instagram_title: "Follow Color Room Films on Instagram"

google_url: "https://plus.google.com/+colorroomfilmsjackson"
google_title: "Visit Color Room Films on Google Plus"

youtube_url: "https://www.youtube.com/channel/UCeeC4ieZCDdZzxIYZeGgHKQ"
youtube_title: "View Color Room Films on YouTube"

vimeo_url: "https://vimeo.com/colorroomfilms"
vimeo_title: "View Color Room Films on Vimeo"

weddingwire_url: "http://www.weddingwire.com/reviews/color-room-films-jackson/fd77ea76d63e4a5f.html"
weddingwire_title: "Read Color Room Films' Reviews on WeddingWire"

theknot_url: "https://www.theknot.com/marketplace/color-room-films-llc-jackson-nj-963435"
theknot_title: "Read Color Room Films' Reviews on The Knot"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Collections config
collections:
  - testimonials
  - weddingvids
  - venuevids
  - corporatelogos

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
